### ISSUE TITLE
CI fails when updating with `apt-get` and installing `tcc`

### ISSUE THREAD

**Issue by ynfle** [exercism/nim-test-runner#127]
https://github.com/exercism/nim-test-runner/runs/5560138192?check_suite_focus=true

**Comment by ee7** [comment]
Looks like this was an intermittent issue, now resolved. 

A Microsoft employee says [the cause was a GitHub Actions outage](https://github-redirect.dependabot.com/microsoft/playwright-github-action/issues/63) and CI [passed on the latest commit](https://github.com/exercism/nim-test-runner/runs/5597025262).

I'll close this issue - please reopen if there's still something to do here.
