### ISSUE TITLE
Feature: Capturing submission output

### ISSUE THREAD

**Issue by ynfle** [exercism/nim-test-runner#13]
# Issue
In keeping with [the interface](https://github.com/exercism/automated-tests/blob/master/docs/interface.md), the test runner needs to expose a way for the user to deliberately output debugging or other information from their code.

## Solutions
1. Capture `stdout` and let the user use `echo`
   1. Wouldn't work for threads
    2. We could let the user call echo and then manipulate the call to directly capture it
2. Expose a new proc (ex. `debug`), with the same interface as echo, that we can use to directly capture the output  
    1. It seems like we'd either have `include` the submitted code into the test file or have a macro that reads their code and puts it in the test file. 
     2. The issue is that the line numbers are for the combined file, not theirs, which isn't much of an issue if we are going to sanitize the stacktraces anyways
    

## Prior Art
- [Python](https:/github.com/exercims/python-test-runner)
  - Uses pytest's native output capturing capabilities _(Not implemented in unittest)_
- [Elixir](https:/github.com/exercims/elixir-test-runner)
  - Outputs a start and stop identifier to stdout for each test and then captures that output that is in between the the identifiers (as per [this](https://exercism-team.slack.com/archives/CMNQSQZUY/p1590976295042100) conversation in Slack)
- [Ruby](https:/github.com/exercims/ruby-test-runner)
  - Adds a method in the global scope to directly capture user output

**Comment by ynfle** [comment]
https://exercism-team.slack.com/archives/CMNQSQZUY/p1590972312033200 For a discussion on this topic

**Comment by ee7** [comment]
Below are some thoughts about the upstream [interface](https://github.com/exercism/automated-tests/blob/master/docs/interface.md) - I noticed that it doesn't seem to support compile-time user output.

For example, consider this test file `plus_test.nim`:
```Nim
import unittest
import plus

suite "Plus":
  test "2 plus 2":
    check plus(2, 2) == 4
````

and this solution `plus.nim`:
```Nim
proc plus*(a, b: int): int =
  static:
    echo "This is compile-time user output."
  echo "This is run-time user output."
  result = a + b
```

Compiling the test file gives:
```
$ nim c --hints:off --verbosity:0 plus_test.nim
This is compile-time user output.
```

and running the produced binary gives:
```
$ ./plus_test
[Suite] Plus
This is run-time user output.
  [OK] 2 plus 2
```

The question: should `results.json` contain the compile-time output? The answer currently seems like "no" (and for our first implementation, should probably be "no" regardless of the spec). That is, we aim for:
```
{
  "status": "pass",
  "tests": [
    {
      "name": "2 plus 2",
      "status": "pass",
      "output": "This is run-time user output."
    }
  ]
}
```

However, Nim is good at compile-time computation, and there could be some good compile-time v3 concept exercises; supporting compile-time user output could be useful eventually. But it's unclear where to put compile-time user output in `results.json` because, for example, the specification says:
- there is no top-level `output` key.
- when their respective status is not `error`, the top-level or per-test `message` keys should be omitted or set to null.

As a thought experiment, imagine instead that the test file is:

```Nim
import plus

static:
  echo "[Suite] Plus"
  let testName = "2 plus 2"
  if plus(2, 2) == 4:
    echo "  [OK] " & testName
  else:
    echo "  [FAILED] " & testName
```

which does something similar to the `unittest` DSL. Then at compile-time we get:
```
nim c --hints:off --verbosity:0 plus_test
This is compile-time user output.
[Suite] Plus
This is run-time user output.
  [OK] 2 plus 2
```

And nothing happens if we execute the binary:
```
$ ./plus_test
```

In this case, should `results.json` be the same?

**Comment by ynfle** [comment]
I think it's more because of how our runner is structured. Why should compile time output be any different?

**Comment by ynfle** [comment]
I think compile-time should not be allowed/captured until we use templates or macros.
What would be the use case for it?

**Comment by ynfle** [comment]
So my thinking is to use `unittest`'s formatter's capabilities to capture the output while the tests are being run. Perhaps like elixir (to inject a statement to `stdout` and then parse it afterward).

**Comment by ynfle** [comment]
I think, for now, the compile-time output should be ignored, especially because it doesn't make sense to put it in on of the tests.

**Comment by ynfle** [comment]
Unless we want to also include compile-time output as part of the `message` field when there is a top-level `fail` or `error` message
